chore: report errors on fork
https://anaconda.atlassian.net/browse/CR-36

diff --git a/.github/workflows/add-repo.yml b/.github/workflows/add-repo.yml
--- a/.github/workflows/add-repo.yml
+++ b/.github/workflows/add-repo.yml
@@ -67,11 +67,14 @@ jobs:
           REPO_LIST: ${{ steps.deps.outputs.feedstocks }}
 
       - name: Fork repo
+        id: fork
         if: ${{ steps.prune.outputs.feedstocks != '' }}
         run: |
+          errorlist=""
           for repo in ${REPO_LIST//,/ }; do
-            gh repo fork https://github.com/conda-forge/$repo --org anaconda-community --clone=false --default-branch-only
+            gh repo fork https://github.com/conda-forge/$repo --org anaconda-community --clone=false --default-branch-only > /dev/null || errorlist+="${feedstock},"
           done
+          echo "errors=$errorlist" >> $GITHUB_OUTPUT
         env:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
           REPO_LIST: ${{ steps.prune.outputs.feedstocks }}
@@ -99,3 +102,37 @@ jobs:
         env:
           REPO_LIST: ${{ steps.deps.outputs.feedstocks  }}
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+
+      - name: Format output
+        id: formatted
+        run: |
+          formatted_errors=$(echo ${ERRORS%,} | yq 'split(",")' -c)
+          echo "errors=$formatted_errors" >> $GITHUB_OUTPUT
+        env:
+          ERRORS: ${{ steps.fork.outputs.errors }}
+
+    outputs:
+      errors: ${{ steps.formatted.outputs.errors }}
+
+  send-dd-error-events:
+    needs: add-repo
+    defaults:
+      run:
+        shell: bash -l {0}
+    runs-on: ubuntu-latest
+    if: ${{ needs.add-repo.outputs.errors != '' }}
+    strategy:
+      matrix:
+        feedstock: ${{ fromJson(needs.add-repo.outputs.errors) }}
+    steps:
+      - name: Send Add Feedstock Error Event
+        uses: masci/datadog@v1
+        with:
+          api-key: ${{ secrets.DATADOG_API_KEY }}
+          events: |
+            - title: "Community Repo Feedstock Creation Error"
+              text: "Feedstock ${{ matrix.feedstock }} failed to fork."
+              alert_type: "error"
+              host: ${{ github.repository_owner }}
+              tags:
+                - "@github.org:anaconda-community"
